// <auto-generated />
namespace SEO_WEB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class deletemetaproperty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deletemetaproperty));
        
        string IMigrationMetadata.Id
        {
            get { return "202103310421444_delete-meta-property"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
