// <auto-generated />
namespace SEO_WEB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class update_attribute_entity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_attribute_entity));
        
        string IMigrationMetadata.Id
        {
            get { return "202103310305174_update_attribute_entity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
